const GOOGLE_STT_MODELS = [
  {
    id: 'chirp_3',
    label: 'Chirp 3',
    category: 'multilingual',
    recommended: true,
    description: 'Latest multilingual model with best quality/speed balance for most use cases.',
  },
  {
    id: 'chirp_2',
    label: 'Chirp 2',
    category: 'multilingual',
    recommended: false,
    description: 'Previous generation multilingual model. Useful for compatibility checks.',
  },
  {
    id: 'telephony',
    label: 'Telephony',
    category: 'phone-call',
    recommended: false,
    description: 'Optimized for call-center style audio and narrowband telephony recordings.',
  },
];

const defaultSharedConfig = {
  transcriptProvider: 'deepgram',
  partialTranscriptEnabled: false,
  deepgramApiKey: '',
  captainDeepgramModel: 'nova-3',
  crewDeepgramModel: 'nova-3',
  googleApiKey: '',
  googleCloudProjectId: '',
  googleTranscriptModel: 'chirp_3',
  googleTranscriptLocation: 'global',
  googleOhmModel: 'gemini-1.5-flash',
  ohmModel: 'gpt',
  ohmFallbackModel: 'gpt',
  ohmWeights: { GREEN: 5, BLUE: 7, RED: 9, PINK: 3 },
  ohmLengthConstraints: {
    veryShort: { maxSentences: 1, maxWords: 25 },
    short: { maxSentences: 2, maxWords: 35 },
    medium: { maxSentences: 3, maxWords: 60 },
    long: { maxSentences: 5, maxWords: 110 },
  },
  ohmLengthCoefficients: {
    veryShort: 1,
    short: 1.5,
    medium: 2,
    long: 2.5,
    overLong: 2.5,
  },
  thirdPartyTranscriptUrl: 'https://ais-dev-msgfyvxutdkvwq3bz4qbhr-148630698694.asia-southeast1.run.app/api/transcribe',
  thirdPartyTranscriptApiKey: '',
  thirdPartyTranscriptModel: '',
  thirdPartyTranscriptAuthScheme: 'bearer',
  ohmAnalysisProvider: 'cvr-measure',
  cvrMeasureBaseUrl: 'https://chunks-cvr-api-781691010426.asia-southeast1.run.app',
  cvrMeasureApiKey: '',
  cvrMeasureTimeoutMs: 45000,
  thirdPartyOhmUrl: 'https://ais-dev-msgfyvxutdkvwq3bz4qbhr-148630698694.asia-southeast1.run.app/api/analyze-ohm',
  thirdPartyOhmApiKey: '',
  thirdPartyOhmModel: '',
  thirdPartyOhmAuthScheme: 'bearer',
  thirdPartyOhmWebhookUrl: '',
  router9ApiKey: '',
  router9BaseUrl: 'http://34.87.121.108:20128/v1',
  router9Model: '',
  router9FallbackModel: '',
  ohmAgentEnabled: false,
  ohmAgentEndpoint: '',
  ohmAgentApiKey: '',
  ohmAgentAuthScheme: 'bearer',
  ohmAgentTimeoutMs: 9000,
  ohmAgentShadowMode: true,
  ohmResponseTiming: {
    fullScoreMs: 1000,
    minScoreMs: 3000,
    minCoefficient: 0,
  },
  meaningStrictness: 'medium',
  meaningWeight: 100,
  feedbackEnabled: true,
  feedbackMode: 'gentle',
  feedbackTone: 'encouraging',
  showGrammarReminder: false,
  showImprovedSentence: false,
  showWhenMeaningCorrect: false,
  onlyIfAffectsClarity: true,
};

module.exports = {
  GOOGLE_STT_MODELS,
  defaultSharedConfig,
};
